export const EMPLOYEE_DASHBOARD_COLUMN_OPTIONS = [
  { value: "daysWorked", label: "Days worked" },
  { value: "dollarInward", label: "Dollar inward" },
  { value: "onboardingAdvance", label: "Onboarding advance" },
  { value: "reimbursements", label: "Employee reimbursements (USD)" },
  { value: "reimbursementLabels", label: "Employee reimbursement labels" },
  { value: "reimbursementsInr", label: "Employee reimbursements (INR)" },
  { value: "appraisalAdvance", label: "Appraisal advance" },
  { value: "appraisalAdvanceInr", label: "Appraisal advance (INR)" },
  { value: "offboardingDeduction", label: "Offboarding deduction" },
  { value: "effectiveDollarInward", label: "Total effective dollar inward (USD)" },
  { value: "cashoutRate", label: "Cashout rate" },
  { value: "cashIn", label: "Total Cash Inward (INR)" },
  { value: "paidRate", label: "Peg rate" },
  { value: "monthlyPaid", label: "Monthly paid (INR)" },
  { value: "actualPaid", label: "Actual paid (INR)" },
  { value: "salaryPaid", label: "Salary paid (INR)" },
  { value: "pf", label: "PF (INR)" },
  { value: "tds", label: "TDS (INR)" },
  { value: "fxCommission", label: "Forex gain (INR)" },
  { value: "commissionEarned", label: "Operating margin (INR)" },
  { value: "grossEarnings", label: "Gross P&L (INR)" },
  { value: "advances", label: "Advances (INR)" },
  { value: "netProfit", label: "Net P/L (INR)" },
];

export const PERIOD_DASHBOARD_COLUMN_OPTIONS = [
  { value: "dollarInward", label: "Dollar inward" },
  { value: "onboardingAdvance", label: "Onboarding advance" },
  { value: "reimbursements", label: "Employee reimbursements (USD)" },
  { value: "reimbursementLabels", label: "Employee reimbursement labels" },
  { value: "reimbursementsInr", label: "Employee reimbursements (INR)" },
  { value: "appraisalAdvance", label: "Appraisal advance" },
  { value: "appraisalAdvanceInr", label: "Appraisal advance (INR)" },
  { value: "offboardingDeduction", label: "Offboarding deduction" },
  { value: "effectiveDollarInward", label: "Total effective dollar inward (USD)" },
  { value: "cashoutRate", label: "Cashout rate" },
  { value: "cashIn", label: "Total Cash Inward (INR)" },
  { value: "paidRate", label: "Peg rate" },
  { value: "monthlyPaid", label: "Monthly paid (INR)" },
  { value: "actualPaid", label: "Actual paid (INR)" },
  { value: "salaryPaid", label: "Salary paid (INR)" },
  { value: "pf", label: "PF (INR)" },
  { value: "tds", label: "TDS (INR)" },
  { value: "fxCommission", label: "Forex gain (INR)" },
  { value: "commissionEarned", label: "Operating margin (INR)" },
  { value: "grossEarnings", label: "Gross P&L (INR)" },
  { value: "expenses", label: "Expenses (INR)" },
  { value: "advances", label: "Advances (INR)" },
  { value: "companyReimbursementUsd", label: "Reimb. (USD)" },
  { value: "companyReimbursementInr", label: "Reimb. (INR)" },
  { value: "netPl", label: "Net P/L (INR)" },
];

export const DEFAULT_EMPLOYEE_DASHBOARD_COLUMNS = [
  "effectiveDollarInward",
  "cashoutRate",
  "cashIn",
  "salaryPaid",
  "pf",
  "tds",
  "fxCommission",
  "commissionEarned",
  "grossEarnings",
  "advances",
  "netProfit",
];

export const DEFAULT_PERIOD_DASHBOARD_COLUMNS = [
  "effectiveDollarInward",
  "cashoutRate",
  "cashIn",
  "salaryPaid",
  "pf",
  "tds",
  "fxCommission",
  "commissionEarned",
  "grossEarnings",
  "expenses",
  "advances",
  "netPl",
];
